[platformio]
default_envs = esp32-c3-devkitm-1

[env:esp32-c3-devkitm-1]
platform = espressif32@7.0.1
board = esp32-c3-devkitm-1
framework = arduino
board_build.partitions = partitions.csv
board_upload.flash_size = 4MB
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
build_unflags = -std=gnu++11
lib_deps =
    jgromes/RadioLib@7.7.1
    adafruit/Adafruit Unified Sensor@1.1.15
    adafruit/DHT sensor library@1.4.7
    bblanchon/ArduinoJson@7.4.2
build_flags =
    -std=gnu++17
    -I include
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=3

[env:hil]
extends = env:esp32-c3-devkitm-1
build_flags =
    ${env:esp32-c3-devkitm-1.build_flags}
    -D GATHRA_FORCE_MAINTENANCE=1

[env:rollback-test]
extends = env:esp32-c3-devkitm-1
build_flags =
    ${env:esp32-c3-devkitm-1.build_flags}
    -D GATHRA_ROLLBACK_TEST_FAIL=1

[env:native]
platform = native@1.2.1
test_framework = unity
test_build_src = no
build_flags =
    -std=gnu++17
    -I include
