#pragma once

namespace gathra::dashboard {

inline constexpr char kHtml[] = R"GATHRAHTML(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>GATHRA Node</title><style>
:root{color-scheme:dark;--bg:#07131c;--card:#102431;--line:#294657;--accent:#20c997;--warn:#ffc857;--bad:#ff6b6b;--text:#e7f2f6;--muted:#9eb5c1}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px system-ui,sans-serif}header{position:sticky;top:0;z-index:2;background:#091a25ee;border-bottom:1px solid var(--line);padding:12px 16px}h1{font-size:20px;margin:0}.sub{color:var(--muted);font-size:12px}main{max-width:1050px;margin:auto;padding:12px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:12px}.card{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:14px;margin-bottom:12px}h2{font-size:17px;margin:0 0 10px}button,input,select{border:1px solid var(--line);border-radius:6px;padding:9px;background:#0b1b25;color:var(--text)}button{background:#176b59;cursor:pointer;font-weight:650;margin:3px}button.danger{background:#853c43}button.secondary{background:#304c5c}button:disabled{opacity:.5}label{display:grid;grid-template-columns:minmax(150px,1fr) minmax(120px,1fr);align-items:center;gap:8px;margin:7px 0;color:var(--muted)}input{width:100%}pre{white-space:pre-wrap;overflow:auto;background:#081720;padding:10px;border-radius:7px;max-height:390px}.notice{border-left:4px solid var(--warn);padding:8px;background:#3a321d;color:#ffe7a4;margin:8px 0}.ok{color:var(--accent)}.bad{color:var(--bad)}canvas{width:100%;height:300px;background:#081720;border-radius:7px}nav{overflow:auto;white-space:nowrap;margin-top:8px}nav a{color:var(--text);margin-right:13px;text-decoration:none}table{width:100%;border-collapse:collapse}td{padding:5px;border-bottom:1px solid var(--line)}td:first-child{color:var(--muted)}#toast{position:fixed;bottom:12px;right:12px;max-width:340px;padding:10px;background:#203d49;border-radius:7px;display:none}small{color:var(--muted)}@media(max-width:500px){label{grid-template-columns:1fr}.card{padding:11px}}
</style></head><body><header><h1>GATHRA Flood Sensor Node</h1><div class="sub">Local maintenance console · Firmware v1</div><nav><a href="#status">Status</a><a href="#measurement">Measure</a><a href="#history">History</a><a href="#config">Config</a><a href="#calibration">Calibration</a><a href="#radio">LoRa</a><a href="#logs">Logs</a><a href="#ota">OTA</a></nav></header>
<main><section id="status" class="card"><h2>Device Status</h2><div id="summary">Loading…</div><details><summary>Complete status JSON</summary><pre id="statusJson"></pre></details></section>
<div class="grid"><section id="measurement" class="card"><h2>Measurement</h2><button onclick="act('/api/measure')">Measure Now</button><pre id="measurementOut">No maintenance measurement yet.</pre></section>
<section id="radio" class="card"><h2>LoRa Diagnostics</h2><button onclick="act('/api/radio/test')">Send Test Packet</button><p><small>No gateway is installed; a bounded missing-ACK result is expected.</small></p><pre id="radioOut"></pre></section></div>
<section id="history" class="card"><h2>RTC Measurement History</h2><label>Series<select id="series" onchange="drawHistory()"><option value="rawDistanceMm">Raw median distance (mm)</option><option value="acceptedDistanceMm">Accepted distance (mm)</option><option value="waterHeightMm">Derived water height (mm)</option><option value="temperatureC">Temperature (°C)</option><option value="humidityPercent">Humidity (%)</option><option value="batteryMv">Battery (mV)</option></select></label><canvas id="chart" width="950" height="300"></canvas><small>X-axis uses retained measurement sequence; rejected/transient raw points are red.</small></section>
<section id="config" class="card"><h2>Runtime Configuration</h2><p><small>GPIO wiring and the maintenance AP password are immutable in v1.</small></p><div id="configForm"></div><button onclick="saveConfig()">Validate &amp; Save Config</button><button class="secondary" onclick="loadConfig()">Reload</button></section>
<section id="calibration" class="card"><h2>Calibration</h2><div class="notice">“Capture current as reference” is only valid when the surface below the sensor represents the intended installation datum.</div><div id="calState"></div><label>Manual reference distance (mm)<input id="referenceInput" type="number" min="20" max="30000"></label><button onclick="setCalibration()">Set Reference</button><button onclick="act('/api/calibration/capture')">Capture Current as Reference</button><button class="secondary" onclick="clearCalibration()">Clear Reference</button><p><small>Installation min/max constraints are edited in Runtime Configuration. Use zero for both to disable them.</small></p></section>
<section id="logs" class="card"><h2>Bounded Recent Logs</h2><pre id="logsOut"></pre></section>
<section id="ota" class="card"><h2>Browser Firmware OTA</h2><div class="notice">Upload a PlatformIO <code>firmware.bin</code>. The inactive OTA slot is written and bootloader rollback remains pending until application boot checks pass.</div><form id="otaForm"><input id="firmware" name="firmware" type="file" accept=".bin,application/octet-stream" required><button type="submit">Upload Firmware</button></form><progress id="otaProgress" max="100" value="0" style="width:100%"></progress><pre id="otaOut"></pre></section>
<section class="card"><h2>Maintenance Controls</h2><button class="danger" onclick="act('/api/reboot')">Reboot</button><button class="danger" onclick="act('/api/maintenance/exit')">Exit Maintenance / Sleep</button><p><small>Holding the physical button for 2 seconds also exits. Passive status/history/log polling does not extend the inactivity timeout.</small></p></section></main><div id="toast"></div>
<script>
let config={},historyData=[];const units={normalWakeIntervalSec:'s',changingWakeIntervalSec:'s',sonarBurstCount:'pings',sonarMinimumValid:'pings',sonarInterPingMs:'ms',hampelWindow:'samples',hampelMultiplier:'×',hampelAbsoluteFloorMm:'mm',suddenChangeThresholdMm:'mm',riseVerificationCount:'observations',riseRequiredConfirmations:'votes',riseVerificationIntervalMs:'ms',riseToleranceMm:'mm',fallVerificationCount:'observations',fallRequiredConfirmations:'votes',fallVerificationIntervalMs:'ms',fallToleranceMm:'mm',emaAlpha:'0–1',referenceDistanceMm:'mm (0=unset)',installationMinimumDistanceMm:'mm (0=disabled)',installationMaximumDistanceMm:'mm (0=disabled)',batteryCalibrationFactor:'×',batteryCalibrationOffsetMv:'mV',batteryLowMv:'mV',batteryCriticalMv:'mV',loraFrequencyMhz:'MHz',loraBandwidthKhz:'kHz',loraSpreadingFactor:'SF',loraCodingRateDenominator:'4/n',loraTxPowerDbm:'dBm',loraSyncWord:'0–255',ackTimeoutMs:'ms',ackRetryCount:'retries',maintenanceTimeoutSec:'s'};
const toast=m=>{let e=document.querySelector('#toast');e.textContent=m;e.style.display='block';setTimeout(()=>e.style.display='none',3500)};
async function json(url,opt){let r=await fetch(url,opt);let t=await r.text(),v;try{v=JSON.parse(t)}catch{v={ok:r.ok,message:t}}if(!r.ok)throw Error(v.error||v.message||r.statusText);return v}
async function loadStatus(){try{let s=await json('/api/status');statusJson.textContent=JSON.stringify(s,null,2);summary.innerHTML=`<table><tr><td>Firmware / build</td><td>${s.firmwareVersion} · ${s.build}</td></tr><tr><td>Node / MAC</td><td>${s.nodeId} · ${s.mac}</td></tr><tr><td>State / wake</td><td>${s.state} · ${s.wakeReason}</td></tr><tr><td>Battery</td><td>${s.measurement.batteryMv??'—'} mV · flags 0x${s.measurement.healthFlags.toString(16)}</td></tr><tr><td>Environment</td><td>${s.measurement.temperatureC??'—'} °C / ${s.measurement.humidityPercent??'—'} %</td></tr><tr><td>Distance raw / accepted</td><td>${s.measurement.rawDistanceMm??'—'} / ${s.measurement.acceptedDistanceMm??'—'} mm</td></tr><tr><td>Filter / MAD</td><td>${s.measurement.filterState} · ${s.measurement.madMm} mm</td></tr><tr><td>LoRa / ACK</td><td>${s.radio.ready?'ready':'error'} · ${s.radio.acknowledged?'ACK':'unacked'} · attempts ${s.radio.attempts}</td></tr><tr><td>RTC history</td><td>${s.history.count}/${s.history.capacity}</td></tr><tr><td>OTA</td><td>${s.ota.partition} · ${s.ota.imageState} · ${s.ota.lastStatus}</td></tr></table>`;calState.textContent=s.calibration.configured?`Reference: ${s.calibration.referenceDistanceMm} mm`:'Reference is not configured; water height is unavailable.'}catch(e){summary.textContent=e.message}}
async function loadHistory(){try{let h=await json('/api/history');historyData=h.entries||[];drawHistory()}catch(e){toast(e.message)}}
function drawHistory(){let c=chart,x=c.getContext('2d'),key=series.value,d=historyData.filter(v=>v[key]!==null&&v[key]!==undefined);x.clearRect(0,0,c.width,c.height);x.fillStyle='#9eb5c1';if(!d.length){x.fillText('No retained values for this series',20,30);return}let vals=d.map(v=>v[key]),lo=Math.min(...vals),hi=Math.max(...vals);if(hi===lo){lo-=1;hi+=1}let px=(i)=>40+i*(c.width-60)/Math.max(1,d.length-1),py=v=>20+(hi-v)*(c.height-50)/(hi-lo);x.strokeStyle='#294657';x.strokeRect(40,20,c.width-60,c.height-50);x.fillText(hi.toFixed(1),3,26);x.fillText(lo.toFixed(1),3,c.height-28);x.beginPath();d.forEach((v,i)=>{let X=px(i),Y=py(v[key]);i?x.lineTo(X,Y):x.moveTo(X,Y)});x.strokeStyle='#20c997';x.lineWidth=2;x.stroke();d.forEach((v,i)=>{x.beginPath();x.arc(px(i),py(v[key]),3,0,7);x.fillStyle=(v.filterState==='TRANSIENT_REJECTED'||v.filterState==='UNCERTAIN')?'#ff6b6b':'#20c997';x.fill()})}
async function loadConfig(){try{config=await json('/api/config');let f=configForm;f.innerHTML='';Object.entries(config).forEach(([k,v])=>{if(k==='schemaVersion')return;let l=document.createElement('label');l.textContent=k+(units[k]?` (${units[k]})`:'');let i=document.createElement('input');i.id='cfg_'+k;i.value=v;i.type=k==='nodeId'?'text':'number';if(typeof v==='number'&&!Number.isInteger(v))i.step='any';l.append(i);f.append(l)});referenceInput.value=config.referenceDistanceMm||''}catch(e){toast(e.message)}}
async function saveConfig(){let c={...config};Object.keys(c).forEach(k=>{let i=document.querySelector('#cfg_'+k);if(i)c[k]=k==='nodeId'?i.value:Number(i.value)});try{let r=await json('/api/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(c)});toast(r.message||'Saved');await loadConfig();await loadStatus()}catch(e){toast(e.message)}}
async function act(url,body){try{let r=await json(url,{method:'POST',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});toast(r.message||'Done');if(url.includes('measure'))measurementOut.textContent=JSON.stringify(r,null,2);if(url.includes('radio'))radioOut.textContent=JSON.stringify(r,null,2);await loadStatus();await loadHistory()}catch(e){toast(e.message)}}
function setCalibration(){act('/api/calibration/set',{referenceDistanceMm:Number(referenceInput.value)})}function clearCalibration(){act('/api/calibration/set',{referenceDistanceMm:0})}
async function loadLogs(){try{let l=await json('/api/logs');logsOut.textContent=(l.lines||[]).join('\n');logsOut.scrollTop=logsOut.scrollHeight}catch{}}
let activityLast=0;function activity(){let n=Date.now();if(n-activityLast<15000)return;activityLast=n;fetch('/api/activity',{method:'POST'}).catch(()=>{})}['pointerdown','keydown','touchstart'].forEach(e=>addEventListener(e,activity,{passive:true}));
otaForm.addEventListener('submit',e=>{e.preventDefault();let f=firmware.files[0];if(!f)return;let data=new FormData();data.append('firmware',f);let x=new XMLHttpRequest();x.open('POST','/api/ota');x.upload.onprogress=e=>{if(e.lengthComputable)otaProgress.value=e.loaded/e.total*100};x.onload=()=>{otaOut.textContent=x.responseText;toast(x.status===200?'OTA accepted; rebooting':'OTA failed')};x.onerror=()=>toast('OTA network error');activity();x.send(data)});
loadStatus();loadHistory();loadConfig();loadLogs();setInterval(loadStatus,3000);setInterval(loadLogs,3000);setInterval(loadHistory,10000);
</script></body></html>)GATHRAHTML";

}  // namespace gathra::dashboard
