#pragma once

namespace gathra::dashboard {

inline constexpr char kHtml[] = R"GATHRAHTML(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>GATHRA Node 2</title><style>
:root{color-scheme:dark;--bg:#07131c;--card:#102431;--line:#294657;--good:#20c997;--warn:#ffc857;--bad:#ff6b6b;--text:#e7f2f6;--muted:#9eb5c1}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px system-ui,sans-serif}header{position:sticky;top:0;z-index:2;background:#091a25ee;border-bottom:1px solid var(--line);padding:12px 16px}h1{font-size:20px;margin:0}.sub,small{color:var(--muted)}main{max-width:1100px;margin:auto;padding:12px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(310px,1fr));gap:12px}.card{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:14px;margin-bottom:12px}h2{font-size:17px;margin:0 0 10px}button,input,select{border:1px solid var(--line);border-radius:6px;padding:9px;background:#0b1b25;color:var(--text)}button{background:#176b59;cursor:pointer;font-weight:650;margin:3px}button.danger{background:#853c43}button.secondary{background:#304c5c}label{display:grid;grid-template-columns:minmax(155px,1fr) minmax(120px,1fr);align-items:center;gap:8px;margin:7px 0;color:var(--muted)}input{width:100%}pre{white-space:pre-wrap;overflow:auto;background:#081720;padding:10px;border-radius:7px;max-height:390px}.notice{border-left:4px solid var(--warn);padding:8px;background:#3a321d;color:#ffe7a4;margin:8px 0}.good{color:var(--good)}.bad{color:var(--bad)}canvas{width:100%;height:300px;background:#081720;border-radius:7px}nav{overflow:auto;white-space:nowrap;margin-top:8px}nav a{color:var(--text);margin-right:13px;text-decoration:none}table{width:100%;border-collapse:collapse}td{padding:5px;border-bottom:1px solid var(--line);vertical-align:top}td:first-child{color:var(--muted);width:42%}#toast{position:fixed;bottom:12px;right:12px;max-width:360px;padding:10px;background:#203d49;border-radius:7px;display:none}@media(max-width:500px){label{grid-template-columns:1fr}.card{padding:11px}}
</style></head><body><header><h1>GATHRA Flood Sensor Node</h1><div class="sub">Firmware 2.1.0 · LoRa Protocol 3 · PCF8563 hard-power maintenance console</div><nav><a href="#status">Power</a><a href="#measurement">Measure</a><a href="#history">History</a><a href="#config">Config</a><a href="#calibration">Calibration</a><a href="#radio">LoRa</a><a href="#logs">Logs</a><a href="#ota">OTA</a></nav></header>
<main><section id="status" class="card"><h2>Power, RTC &amp; Protocol Status</h2><div class="notice">Maintenance has a fixed five-minute energy deadline. Dashboard polling does not extend it.</div><div id="summary">Loading…</div><details><summary>Complete diagnostics (including recent power events)</summary><pre id="statusJson"></pre></details></section>
<div class="grid"><section id="measurement" class="card"><h2>Measurement</h2><button onclick="act('/api/measure')">Measure Now</button><pre id="measurementOut">No maintenance measurement yet.</pre></section><section id="radio" class="card"><h2>LoRa Protocol 3 Diagnostics</h2><button onclick="act('/api/radio/test')">Send Test Packet</button><pre id="radioOut"></pre></section></div>
<section id="history" class="card"><h2>NVS Measurement History</h2><label>Series<select id="series" onchange="drawHistory()"><option value="rawDistanceMm">Raw median distance (mm)</option><option value="acceptedDistanceMm">Accepted distance (mm)</option><option value="waterHeightMm">Derived water height (mm)</option><option value="temperatureC">Temperature (°C)</option><option value="humidityPercent">Humidity (%)</option><option value="batteryMv">Battery (mV)</option></select></label><canvas id="chart" width="1000" height="300"></canvas><small>Entries survive full power removal. X-axis follows persistent telemetry sequence; trusted UTC is retained per entry.</small></section>
<section id="config" class="card"><h2>Persistent Configuration</h2><p><small>Poll interval is PCF8563 minute resolution (1–255). GPIO assignments and AP password are immutable.</small></p><div id="configForm"></div><button onclick="saveConfig()">Validate &amp; Save</button><button class="secondary" onclick="loadConfig()">Reload</button></section>
<section id="calibration" class="card"><h2>Calibration</h2><div class="notice">Capture is only valid when the current surface represents the installation datum.</div><div id="calState"></div><label>Reference distance (mm)<input id="referenceInput" type="number" min="0" max="30000"></label><button onclick="setCalibration()">Set Reference</button><button onclick="act('/api/calibration/capture')">Capture Current</button><button class="secondary" onclick="clearCalibration()">Clear</button></section>
<section id="logs" class="card"><h2>Bounded Recent Logs</h2><pre id="logsOut"></pre></section>
<section id="ota" class="card"><h2>Dual-Slot Browser OTA</h2><div class="notice">The Node persists OTA_REBOOT and verifies the active PCF level latch before reboot. Bootloader rollback remains pending until application checks pass.</div><form id="otaForm"><input id="firmware" name="firmware" type="file" accept=".bin,application/octet-stream" required><button type="submit">Upload Firmware</button></form><progress id="otaProgress" max="100" value="0" style="width:100%"></progress><pre id="otaOut"></pre></section>
<section class="card"><h2>Maintenance Controls</h2><button class="danger" onclick="maintenanceReboot()">Reboot in Maintenance</button><button class="danger" onclick="powerOff()">Finish &amp; Power Off</button><p><small>Power-off programs and verifies the next PCF timer/alarm before clearing the active latch flag. USB power can keep the ESP alive and is not proof of battery-rail power removal.</small></p></section></main><div id="toast"></div>
<script>
let config={},historyData=[];const $=id=>document.getElementById(id);const units={pollIntervalMinutes:'min (1–255)',sonarBurstCount:'pings',sonarMinimumValid:'pings',sonarInterPingMs:'ms',hampelWindow:'samples',hampelMultiplier:'×',hampelAbsoluteFloorMm:'mm',suddenChangeThresholdMm:'mm',riseVerificationCount:'observations',riseRequiredConfirmations:'votes',riseVerificationIntervalMs:'ms',riseToleranceMm:'mm',fallVerificationCount:'observations',fallRequiredConfirmations:'votes',fallVerificationIntervalMs:'ms',fallToleranceMm:'mm',emaAlpha:'0–1',referenceDistanceMm:'mm (0=unset)',installationMinimumDistanceMm:'mm (0=disabled)',installationMaximumDistanceMm:'mm (0=disabled)',batteryCalibrationFactor:'×',batteryCalibrationOffsetMv:'mV',batteryLowMv:'mV',batteryCriticalMv:'mV',loraFrequencyMhz:'MHz',loraBandwidthKhz:'kHz',loraSpreadingFactor:'SF',loraCodingRateDenominator:'4/n',loraTxPowerDbm:'dBm',loraSyncWord:'0–255',ackTimeoutMs:'ms',ackRetryCount:'retries',maintenanceTimeoutSec:'s (60–300)'};
const utc=v=>v?new Date(v*1000).toISOString():'—';const toast=m=>{let e=$('toast');e.textContent=m;e.style.display='block';setTimeout(()=>e.style.display='none',3500)};async function json(url,opt){let r=await fetch(url,opt),t=await r.text(),v;try{v=JSON.parse(t)}catch{v={message:t}}if(!r.ok)throw Error(v.error||v.message||r.statusText);return v}
async function loadStatus(){try{let s=await json('/api/status');$('statusJson').textContent=JSON.stringify(s,null,2);let p=s.pcf8563,r=s.rtc,w=s.power,m=s.maintenance,q=s.protocol,c=s.lastCommand,x=s.measurement;$('summary').innerHTML=`<table><tr><td>Firmware / protocol</td><td>${s.firmwareVersion} / ${s.protocolVersion} · ${s.build}</td></tr><tr><td>Node / MAC</td><td>${s.nodeId} · ${s.mac}</td></tr><tr><td>Boot / app state</td><td>${s.bootReason} · ${s.state}</td></tr><tr><td>Maintenance</td><td>${m.source} · <b>${m.remainingSeconds}s remaining</b></td></tr><tr><td>PCF8563</td><td class="${p.communicationOkay?'good':'bad'}">${p.communicationOkay?'connected':'I²C error'} · C2 0x${p.controlStatus2.toString(16).padStart(2,'0')} · TF ${+p.timerFlag} / AF ${+p.alarmFlag} · ${p.levelMode?'level':'pulse'}</td></tr><tr><td>RTC UTC / validity</td><td>${utc(r.utcUnix)} · ${r.state} · last sync ${utc(r.lastSuccessfulSyncUtc)}</td></tr><tr><td>Normal poll / next</td><td>${w.pollIntervalMinutes} min · ${utc(w.nextExpectedPollUtc)}</td></tr><tr><td>Maintenance schedule</td><td>${w.scheduleState} · ${utc(w.scheduledMaintenanceUtc)}</td></tr><tr><td>Power-off readiness</td><td>${w.powerOffReadiness}</td></tr><tr><td>Persistent protocol</td><td>session ${q.persistentSessionId} · next sequence ${q.nextSequence}</td></tr><tr><td>Last command</td><td>#${c.commandId} ${c.type} · ${c.phase} / ${c.result}</td></tr><tr><td>Measurement</td><td>${x.rawDistanceMm??'—'} / ${x.acceptedDistanceMm??'—'} mm · battery ${x.batteryMv||'—'} mV</td></tr><tr><td>NVS history</td><td>${s.history.count}/${s.history.capacity} · ${s.history.entryBytes} bytes/record</td></tr><tr><td>LoRa ACK</td><td>${s.radio.ready?'ready':'error'} · ${s.radio.acknowledged?'ACK':'unacked'} · attempts ${s.radio.attempts}</td></tr><tr><td>OTA</td><td>${s.ota.partition} · ${s.ota.imageState} · ${s.ota.lastStatus}</td></tr></table>`;$('calState').textContent=s.calibration.configured?`Reference: ${s.calibration.referenceDistanceMm} mm`:'Reference is unset; water height is unavailable.'}catch(e){$('summary').textContent=e.message}}
async function loadHistory(){try{let h=await json('/api/history');historyData=h.entries||[];drawHistory()}catch(e){toast(e.message)}}function drawHistory(){let c=$('chart'),x=c.getContext('2d'),key=$('series').value,d=historyData.filter(v=>v[key]!==null&&v[key]!==undefined);x.clearRect(0,0,c.width,c.height);x.fillStyle='#9eb5c1';if(!d.length){x.fillText('No persistent values for this series',20,30);return}let vals=d.map(v=>v[key]),lo=Math.min(...vals),hi=Math.max(...vals);if(hi===lo){lo-=1;hi+=1}let px=i=>45+i*(c.width-65)/Math.max(1,d.length-1),py=v=>20+(hi-v)*(c.height-50)/(hi-lo);x.strokeStyle='#294657';x.strokeRect(45,20,c.width-65,c.height-50);x.fillText(hi.toFixed(1),3,26);x.fillText(lo.toFixed(1),3,c.height-28);x.beginPath();d.forEach((v,i)=>i?x.lineTo(px(i),py(v[key])):x.moveTo(px(i),py(v[key])));x.strokeStyle='#20c997';x.lineWidth=2;x.stroke();d.forEach((v,i)=>{x.beginPath();x.arc(px(i),py(v[key]),3,0,7);x.fillStyle=(v.filterState==='TRANSIENT_REJECTED'||v.filterState==='UNCERTAIN')?'#ff6b6b':'#20c997';x.fill()})}
async function loadConfig(){try{config=await json('/api/config');let f=$('configForm');f.innerHTML='';Object.entries(config).forEach(([k,v])=>{if(k==='schemaVersion')return;let l=document.createElement('label');l.textContent=k+(units[k]?` (${units[k]})`:'');let i=document.createElement('input');i.id='cfg_'+k;i.value=v;i.type=k==='nodeId'?'text':'number';if(typeof v==='number'&&!Number.isInteger(v))i.step='any';if(k==='pollIntervalMinutes'){i.min=1;i.max=255}if(k==='maintenanceTimeoutSec'){i.min=60;i.max=300}l.append(i);f.append(l)});$('referenceInput').value=config.referenceDistanceMm||''}catch(e){toast(e.message)}}async function saveConfig(){let c={...config};Object.keys(c).forEach(k=>{let i=$('cfg_'+k);if(i)c[k]=k==='nodeId'?i.value:Number(i.value)});try{let r=await json('/api/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(c)});toast(r.message||'Saved');await loadConfig();await loadStatus()}catch(e){toast(e.message)}}
async function act(url,body){try{let r=await json(url,{method:'POST',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});toast(r.message||'Done');if(url.includes('measure'))$('measurementOut').textContent=JSON.stringify(r,null,2);if(url.includes('radio'))$('radioOut').textContent=JSON.stringify(r,null,2);await loadStatus();await loadHistory()}catch(e){toast(e.message)}}function setCalibration(){act('/api/calibration/set',{referenceDistanceMm:Number($('referenceInput').value)})}function clearCalibration(){act('/api/calibration/set',{referenceDistanceMm:0})}function maintenanceReboot(){if(confirm('Reboot while retaining the PCF maintenance latch?'))act('/api/reboot')}function powerOff(){if(confirm('Finish maintenance and release external power after the next wake is verified?'))act('/api/maintenance/exit')}
async function loadLogs(){try{let l=await json('/api/logs');$('logsOut').textContent=(l.lines||[]).join('\n');$('logsOut').scrollTop=$('logsOut').scrollHeight}catch{}}
$('otaForm').addEventListener('submit',e=>{e.preventDefault();let f=$('firmware').files[0];if(!f||!confirm('Install this image and reboot while retaining the RTC latch?'))return;let data=new FormData();data.append('firmware',f);let x=new XMLHttpRequest();x.open('POST','/api/ota');x.upload.onprogress=e=>{if(e.lengthComputable)$('otaProgress').value=e.loaded/e.total*100};x.onload=()=>{$('otaOut').textContent=x.responseText;toast(x.status===200?'OTA accepted; rebooting':'OTA failed')};x.onerror=()=>toast('OTA network error');x.send(data)});
loadStatus();loadHistory();loadConfig();loadLogs();setInterval(loadStatus,3000);setInterval(loadLogs,3000);setInterval(loadHistory,10000);
</script></body></html>)GATHRAHTML";

}  // namespace gathra::dashboard
